const faker = require("@faker-js/faker").faker;

const users = [
  {
    name: "Jane Doe",
    email: "admin@test.fr",
    password: "123456",
    role: 0,
  },
  {
    name: "Joe Doe",
    email: "redacteur@test.fr",
    password: "123456",
    role: 1,
  },
  {
    name: "John Doe",
    email: "contributeur@test.fr",
    password: "123456",
    role: 2,
  },
];

const odonates = [
  {
    scientific_name: "Chalcolestes",
    author_and_year: "Kennedy, 1920",
    french_name: "Leste (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Chalcolestes viridis",
    author_and_year: "(Vander Linden, 1825)",
    french_name: "Leste vert occidental (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Lestes",
    author_and_year: "Leach, 1815",
    french_name: "Leste (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Lestes barbarus",
    author_and_year: "(Fabricius, 1798)",
    french_name: "Leste sauvage (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Lestes dryas",
    author_and_year: "Kirby, 1890",
    french_name: "Leste des bois (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Lestes macrostigma",
    author_and_year: "(Eversmann, 1836)",
    french_name: "Leste à grands stigmas (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Lestes sponsa",
    author_and_year: "(Hansemann, 1823)",
    french_name: "Leste fiancé (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Lestes virens",
    author_and_year: "(Charpentier, 1825)",
    french_name: "Leste verdoyant (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Lestes virens virens",
    author_and_year: "(Charpentier, 1825)",
    french_name: "Leste verdoyant méridional (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Lestes virens vestalis",
    author_and_year: "Rambur, 1842",
    french_name: "Leste verdoyant septentrional (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Sympecma",
    author_and_year: "Burmeister, 1839",
    french_name: "Leste (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Sympecma fusca",
    author_and_year: "(Vander Linden, 1820)",
    french_name: "Leste brun (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Sympecma paedisca",
    author_and_year: "(Brauer, 1877)",
    french_name: "Leste enfant (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Lestidae Calvert, 1901",
  },
  {
    scientific_name: "Calopteryx",
    author_and_year: "Leach, 1815",
    french_name: "Caloptéryx (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Calopterygidae Selys, 1850",
  },
  {
    scientific_name: "Calopteryx haemorrhoidalis",
    author_and_year: "(Vander Linden, 1825)",
    french_name: "Caloptéryx hémorroïdal (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Calopterygidae Selys, 1850",
  },
  {
    scientific_name: "Calopteryx splendens",
    author_and_year: "(Harris, 1780)",
    french_name: "Caloptéryx éclatant (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Calopterygidae Selys, 1850",
  },
  {
    scientific_name: "Calopteryx virgo",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Caloptéryx vierge (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Calopterygidae Selys, 1850",
  },
  {
    scientific_name: "Calopteryx virgo virgo",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Caloptéryx vierge septentrional (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Calopterygidae Selys, 1850",
  },
  {
    scientific_name: "Calopteryx virgo meridionalis",
    author_and_year: "Selys, 1873",
    french_name: "Caloptéryx vierge méridional (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Calopterygidae Selys, 1850",
  },
  {
    scientific_name: "Calopteryx xanthostoma",
    author_and_year: "(Charpentier, 1825)",
    french_name: "Caloptéryx occitan (le)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Calopterygidae Selys, 1850",
  },
  {
    scientific_name: "Platycnemis",
    author_and_year: "Burmeister, 1839",
    french_name: "Agrion (l')",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Platycnemididae Tillyard,1917",
  },
  {
    scientific_name: "Platycnemis acutipennis",
    author_and_year: "Selys, 1841",
    french_name: "Agrion orangé (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Platycnemididae Tillyard,1917",
  },
  {
    scientific_name: "Platycnemis latipes",
    author_and_year: "Rambur, 1842",
    french_name: "Agrion blanchâtre (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Platycnemididae Tillyard,1917",
  },
  {
    scientific_name: "Platycnemis pennipes",
    author_and_year: "(Pallas, 1771)",
    french_name: "Agrion à larges pattes (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Platycnemididae Tillyard,1917",
  },
  {
    scientific_name: "Ceriagrion",
    author_and_year: "Selys, 1876",
    french_name: "Agrion (l')",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Ceriagrion tenellum",
    author_and_year: "(Villers, 1789)",
    french_name: "Agrion délicat (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion",
    author_and_year: "Kirby, 1890",
    french_name: "Agrion (l')",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion caerulescens",
    author_and_year: "(Fonscolombe, 1838)",
    french_name: "Agrion bleuissant (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion hastulatum",
    author_and_year: "(Charpentier, 1825)",
    french_name: "Agrion hasté (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion lunulatum",
    author_and_year: "(Charpentier, 1840)",
    french_name: "Agrion à lunules (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion mercuriale",
    author_and_year: "(Charpentier, 1840)",
    french_name: "Agrion de Mercure (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion ornatum",
    author_and_year: "(Selys, 1850)",
    french_name: "Agrion orné (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion puella",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Agrion jouvencelle (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion pulchellum",
    author_and_year: "(Vander Linden, 1825)",
    french_name: "Agrion joli (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Coenagrion scitulum",
    author_and_year: "(Rambur, 1842)",
    french_name: "Agrion mignon (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Enallagma",
    author_and_year: "Charpentier, 1840",
    french_name: "Agrion (l')",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Enallagma cyathigerum",
    author_and_year: "(Charpentier, 1840)",
    french_name: "Agrion porte-coupe (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Erythromma",
    author_and_year: "Charpentier, 1840",
    french_name: "Naïade (la)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Erythromma lindenii",
    author_and_year: "(Selys, 1840)",
    french_name: "Naïade de Vander Linden (la)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Erythromma najas",
    author_and_year: "(Hansemann, 1823)",
    french_name: "Naïade aux yeux rouges (la)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Erythromma viridulum",
    author_and_year: "(Charpentier, 1840)",
    french_name: "Naïade au corps vert (la)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Ischnura",
    author_and_year: "Charpentier, 1840",
    french_name: "Agrion (l')",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Ischnura elegans",
    author_and_year: "(Vander Linden, 1820)",
    french_name: "Agrion élégant (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Ischnura pumilio",
    author_and_year: "(Charpentier, 1825)",
    french_name: "Agrion nain (l’)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Nehalennia",
    author_and_year: "Selys, 1850",
    french_name: "Déesse (la)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Nehalennia speciosa",
    author_and_year: "(Charpentier, 1840)",
    french_name: "Déesse précieuse (la)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Pyrrhosoma",
    author_and_year: "Charpentier, 1840",
    french_name: "Petite nymphe",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Pyrrhosoma nymphula",
    author_and_year: "(Sulzer, 1776)",
    french_name: "Petite nymphe au corps de feu (la)",
    suborder: "ZYGOPTERA Selys, 1854",
    family: "Coenagrionidae Kirby, 1890",
  },
  {
    scientific_name: "Aeshna",
    author_and_year: "Fabricius, 1775",
    french_name: "Aeschne (l')",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Aeshna affinis",
    author_and_year: "Vander Linden, 1820",
    french_name: "Aeschne affine (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Aeshna caerulea",
    author_and_year: "(Ström, 1783)",
    french_name: "Aeschne azurée (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Aeshna cyanea",
    author_and_year: "(O.F. Müller, 1764)",
    french_name: "Aeschne bleue (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Aeshna grandis",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Grande Aeschne (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Aeshna juncea",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Aeschne des joncs (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Aeshna mixta",
    author_and_year: "Latreille, 1805",
    french_name: "Aeschne mixte (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Anax",
    author_and_year: "Leach in Brewster, 1815",
    french_name: "Anax (l')",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Anax ephippiger",
    author_and_year: "(Burmeister, 1839)",
    french_name: "Anax porte-selle (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Anax imperator",
    author_and_year: "Leach in Brewster, 1815",
    french_name: "Anax empereur (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Anax parthenope",
    author_and_year: "(Selys, 1839)",
    french_name: "Anax napolitain (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Boyeria",
    author_and_year: "McLachlan, 1896",
    french_name: "Aeschne (l')",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Boyeria irene",
    author_and_year: "(Fonscolombe, 1838)",
    french_name: "Aeschne paisible (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Brachytron",
    author_and_year: "Evans, 1845",
    french_name: "Aeschne (l')",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Brachytron pratense",
    author_and_year: "(O.F. Müller, 1764)",
    french_name: "Aeschne printanière (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Isoaeschna",
    author_and_year:
      "Schneider, Vierstraete, Kosterin, Ikemeyer, Hu, Snegovaya & Dumont, 2023",
    french_name: "Aeschne (l')",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Isoaeschna isoceles",
    author_and_year: "(O.F. Müller, 1767)",
    french_name: "Aeschne isocèle (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Aeshnidae Rambur, 1842",
  },
  {
    scientific_name: "Gomphus",
    author_and_year: "Leach in Brewster, 1815",
    french_name: "Gomphe (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Gomphus graslinii",
    author_and_year: "Rambur, 1842",
    french_name: "Gomphe de Graslin (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Gomphus pulchellus",
    author_and_year: "Selys, 1840",
    french_name: "Gomphe joli (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Gomphus simillimus",
    author_and_year: "Selys, 1840",
    french_name: "Gomphe semblable (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Gomphus vulgatissimus",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Gomphe vulgaire (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Onychogomphus",
    author_and_year: "Selys, 1854",
    french_name: "Gomphe (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Onychogomphus forcipatus",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Gomphe à pinces (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Onychogomphus forcipatus forcipatus",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Gomphe à pinces septentrional (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Onychogomphus forcipatus unguiculatus",
    author_and_year: "(Vander Linden, 1820)",
    french_name: "Gomphe à pinces méridional (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Onychogomphus uncatus",
    author_and_year: "(Charpentier, 1840)",
    french_name: "Gomphe à crochets (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Ophiogomphus",
    author_and_year: "Selys, 1854",
    french_name: "Gomphe (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Ophiogomphus cecilia",
    author_and_year: "(Geoffroy in Fourcroy, 1785)",
    french_name: "Gomphe serpentin (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Stylurus",
    author_and_year: "Needham, 1897",
    french_name: "Gomphe (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Stylurus flavipes",
    author_and_year: "(Charpentier, 1825)",
    french_name: "Gomphe à pattes jaunes (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Gomphidae Rambur, 1842",
  },
  {
    scientific_name: "Cordulegaster",
    author_and_year: "Leach in Brewster, 1815",
    french_name: "Cordulégastre (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Cordulegastridae Hagen, 1875",
  },
  {
    scientific_name: "Cordulegaster bidentata",
    author_and_year: "Selys, 1843",
    french_name: "Cordulégastre bidenté (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Cordulegastridae Hagen, 1875",
  },
  {
    scientific_name: "Cordulegaster boltonii",
    author_and_year: "(Donovan, 1807)",
    french_name: "Cordulégastre annelé (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Cordulegastridae Hagen, 1875",
  },
  {
    scientific_name: "Oxygastra",
    author_and_year: "Selys, 1870",
    french_name: "Cordulie (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "incertae sedis",
  },
  {
    scientific_name: "Oxygastra curtisii",
    author_and_year: "(Dale, 1834)",
    french_name: "Cordulie à corps fin (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "incertae sedis",
  },
  {
    scientific_name: "Macromiidae",
    author_and_year: "Needham, 1903",
    french_name: "Macromidés",
    suborder: "ANISOPTERA Selys 1854",
    family: "incertae sedis",
  },
  {
    scientific_name: "Macromia",
    author_and_year: "Rambur, 1842",
    french_name: "Cordulie (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "incertae sedis",
  },
  {
    scientific_name: "Macromia splendens",
    author_and_year: "(Pictet, 1843)",
    french_name: "Cordulie splendide (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "incertae sedis",
  },
  {
    scientific_name: "Cordulia",
    author_and_year: "Leach in Brewster, 1815",
    french_name: "Cordulie (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Cordulia aenea",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Cordulie bronzée (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Epitheca",
    author_and_year: "Charpentier, 1840",
    french_name: "Cordulie (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Epitheca bimaculata",
    author_and_year: "(Charpentier, 1825)",
    french_name: "Cordulie à deux taches (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Somatochlora",
    author_and_year: "Selys, 1871",
    french_name: "Cordulie (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Somatochlora alpestris",
    author_and_year: "(Selys, 1840)",
    french_name: "Cordulie alpestre (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Somatochlora arctica",
    author_and_year: "(Zetterstedt, 1840)",
    french_name: "Cordulie arctique (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Somatochlora flavomaculata",
    author_and_year: "(Vander Linden, 1825)",
    french_name: "Cordulie à taches jaunes (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Somatochlora metallica",
    author_and_year: "(Vander Linden, 1825)",
    french_name: "Cordulie métallique (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Corduliidae Kirby, 1890",
  },
  {
    scientific_name: "Crocothemis",
    author_and_year: "Brauer, 1868",
    french_name: "Libellule (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Crocothemis erythraea",
    author_and_year: "(Brullé, 1832)",
    french_name: "Libellule écarlate (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Leucorrhinia",
    author_and_year: "Brittinger, 1850",
    french_name: "Leucorrhine (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Leucorrhinia albifrons",
    author_and_year: "(Burmeister, 1839)",
    french_name: "Leucorrhine à front blanc (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Leucorrhinia caudalis",
    author_and_year: "(Charpentier, 1840)",
    french_name: "Leucorrhine à large queue (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Leucorrhinia dubia",
    author_and_year: "(Vander Linden, 1825)",
    french_name: "Leucorrhine douteuse (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Leucorrhinia pectoralis",
    author_and_year: "(Charpentier, 1825)",
    french_name: "Leucorrhine à gros thorax (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Libellula",
    author_and_year: "Linnaeus, 1758",
    french_name: "Libellule (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Libellula depressa",
    author_and_year: "Linnaeus, 1758",
    french_name: "Libellule déprimée (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Libellula fulva",
    author_and_year: "O.F. Müller, 1764",
    french_name: "Libellule fauve (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Libellula quadrimaculata",
    author_and_year: "Linnaeus, 1758",
    french_name: "Libellule à quatre taches (la)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Orthetrum",
    author_and_year: "Newman, 1833",
    french_name: "Orthétrum (l')",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Orthetrum albistylum",
    author_and_year: "(Selys, 1848)",
    french_name: "Orthétrum à stylets blancs (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Orthetrum brunneum",
    author_and_year: "(Fonscolombe, 1837)",
    french_name: "Orthétrum brun (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Orthetrum cancellatum",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Orthétrum réticulé (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Orthetrum coerulescens",
    author_and_year: "(Fabricius, 1798)",
    french_name: "Orthétrum bleuissant (l’)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum",
    author_and_year: "Newman, 1833",
    french_name: "Sympétrum (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum danae",
    author_and_year: "(Sulzer, 1776)",
    french_name: "Sympétrum noir (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum depressiusculum",
    author_and_year: "(Selys, 1841)",
    french_name: "Sympétrum déprimé (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum flaveolum",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Sympétrum jaune d’or (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum fonscolombii",
    author_and_year: "(Selys, 1840)",
    french_name: "Sympétrum de Fonscolombe (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum meridionale",
    author_and_year: "(Selys, 1841)",
    french_name: "Sympétrum méridional (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum pedemontanum",
    author_and_year: "(O.F. Müller in Allioni, 1766)",
    french_name: "Sympétrum du Piémont (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum sanguineum",
    author_and_year: "(O.F. Müller, 1764)",
    french_name: "Sympétrum rouge-sang (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum striolatum",
    author_and_year: "(Charpentier, 1840)",
    french_name: "Sympétrum strié (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Sympetrum vulgatum",
    author_and_year: "(Linnaeus, 1758)",
    french_name: "Sympétrum vulgaire (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Trithemis",
    author_and_year: "Brauer, 1868",
    french_name: "Trithémis (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Trithemis annulata",
    author_and_year: "(Palisot de Beauvois, 1807)",
    french_name: "Trithémis pourpré (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
  {
    scientific_name: "Trithemis kirbyi",
    author_and_year: "Selys, 1891",
    french_name: "Trithémis ambré (le)",
    suborder: "ANISOPTERA Selys 1854",
    family: "Libellulidae Leach in Brewster, 1815",
  },
];

const publications = [
  {
    title:
      "Nomenclature française des appendices anaux des imagos et larves d’odonates : pour l’abandon du terme « cercoïdes »",
    author: "Piney, B. & Krieg-Jacquier, R.",
    year: "(2023)",
    journal: "Martinia",
    book_citation: "",
    volume: "38",
    number: "(1)",
    editor: "",
    link: "https://martinia.insectes.org/nomenclature-francaise-des-appendices-anaux-des-imagos-et-larves-dodonates-pour-labandon-du-terme-cercoides/",
  },
  {
    title:
      "Odonatopteran Approaches to the Challenges of Flight: Convergence of Responses Subject to a Common Set of Morphological Constraints",
    author: "Nel, A., & Piney, B.",
    year: "(2023)",
    journal: "",
    book_citation:
      "In Bels,V. & Russell, A. (eds) Convergent Evolution: Animal Form and Function (p. 21-36). Springer, Cham",
    volume: "",
    number: "",
    editor: "Springer, Cham",
    link: "https://doi.org/10.1007/978-3-031-11441-0_2",
  },
  {
    title: "Convergent Evolution: Animal Form and Function",
    author: "Bels,V. & Russell, A. (eds)",
    year: "(2023)",
    journal: "",
    book_citation: "",
    volume: "",
    number: "",
    editor: "Springer, Cham",
    link: "https://doi.org/10.1007/978-3-031-11441-0",
  },
  {
    title: "En guise d'habitats, quelques lignes d'écologie",
    author: "Ulmer, A,",
    year: "(2022)",
    journal: "",
    book_citation:
      "In Deliry, C., Noally, L. & Ulmer, A. (dir.). Libellules et Demoiselles de la Loire. Atlas des Odonates du département de la Loire. Groupe Sympetrum & FNE Loire",
    volume: "",
    number: "",
    editor: "Groupe Sympetrum & FNE Loire",
    link: "",
  },
  {
    title: "Orthetrum albistylum",
    author: "Noally, L.",
    year: "(2022)",
    journal: "",
    book_citation:
      "In Deliry, C., Noally, L. & Ulmer, A. (dir.). Libellules et Demoiselles de la Loire. Atlas des Odonates du département de la Loire. Groupe Sympetrum & FNE Loire",
    volume: "",
    number: "",
    editor: "Groupe Sympetrum & FNE Loire",
    link: "",
  },
  {
    title:
      "Libellules et Demoiselles de la Loire. Atlas des Odonates du département de la Loire",
    author: "Deliry, C., Noally, L. & Ulmer, A. (dir.)",
    year: "(2022)",
    journal: "",
    book_citation: "",
    volume: "",
    number: "",
    editor: "Groupe Sympetrum & FNE Loire",
    link: "",
  },
  {
    title:
      "The oldest-known Lestidae (Odonata) from the late Eocene of Tibet: Palaeoclimatic implications",
    author:
      "Xia, G., Zheng, D., Krieg-Jacquier, R., Fan, Q., Chen, Y., & Nel, A.",
    year: "(2021)",
    journal: "Geological Magazine",
    book_citation: "",
    volume: "159",
    number: "(4)",
    editor: "",
    link: "https://doi.org/10.1017/S0016756821001102",
  },
  {
    title: "",
    author: "",
    year: "(2021)",
    journal: "Martinia",
    book_citation: "",
    volume: "35",
    number: "",
    editor: "Office pour les insectes et leur environnement (Opie)",
    link: "https://martinia.insectes.org/archives-annuelles/?y=2021",
  },
  {
    title: "",
    author: "",
    year: "(2013)",
    journal: "Sympetrum",
    book_citation: "",
    volume: "17",
    number: "",
    editor: "Groupe Sympetrum",
    link: "https://deliry.wtf.org/revue-sympetrum/?y=2023",
  },
  {
    title:
      "Le Rhône, du glacier de la Furka au delta de la Camargue. Les Odonates d'un grand fleuve européen.",
    author: "Deliry, C., Pont, B., Faton, J.-M., Ladet, A. & Oertli, B.",
    year: "(2013)",
    journal: "Sympetrum",
    book_citation: "",
    volume: "17",
    number: "",
    editor: "",
    link: "https://deliry.wtf.org/revue-sympetrum/?y=2023/dans_ma_troupe_on_est_les_meilleurs,pdf",
  },
];

const settings = {
  members: 221,
  odonates_data: 185,
  actions: 96,
  posted_publications: 50,
};

const categories = [
  {
    id: 1,
    name: "Général",
    slug: "general",
  },
  {
    id: 2,
    name: "Ain",
    slug: "ain",
  },
  {
    id: 3,
    name: "Ardèche",
    slug: "ardeche",
  },
  {
    id: 4,
    name: "Drôme",
    slug: "drome",
  },
  {
    id: 5,
    name: "Isère",
    slug: "isere",
  },
  {
    id: 6,
    name: "Loire",
    slug: "loire",
  },
  {
    id: 7,
    name: "Rhône",
    slug: "rhone",
  },
  {
    id: 8,
    name: "Savoie",
    slug: "savoie",
  },
  {
    id: 9,
    name: "Haute-Savoie",
    slug: "haute-savoie",
  },
];

const tags = [
  {
    id: 1,
    name: "Ecologie",
    slug: "ecologie",
  },
  {
    id: 2,
    name: "Habitat",
    slug: "habitat",
  },
  {
    id: 3,
    name: "Evènement",
    slug: "evenement",
  },
  {
    id: 4,
    name: "Association",
    slug: "association",
  },
  {
    id: 5,
    name: "Vie locale",
    slug: "vie-locale",
  },
  {
    id: 6,
    name: "Identification",
    slug: "identification",
  },
];

const newsletterEmails = [
  {
    id: 1,
    email: "theomaillard69@gmail.com",
  },
];

const generateRandomTags = (min, max, count) => {
  const tags = new Set();
  while (tags.size < count) {
    tags.add(faker.number.int({ min, max }));
  }
  return Array.from(tags);
};

const generateArticles = (numArticles) => {
  console.log("Generating fake articles...");
  const articles = [];
  for (let i = 1; i <= numArticles; i++) {
    const intro = faker.lorem.paragraph(); // Générer une introduction
    const introCut = intro.substring(0, 160); // Limiter à 140 caractère
    articles.push({
      id: i,
      title: faker.lorem.sentence(),
      slug: `article-blog-test-${i}`,
      image_url: `https://sympetrum.s3.eu-west-3.amazonaws.com/mediatheque/blog-details.jpg`,
      intro: introCut,
      content: `<h2>${faker.lorem.sentence()}</h2><p>${faker.lorem.paragraph()}</p>`,
      publication_date: faker.date.recent().toISOString(),
      category_id: faker.number.int({ min: 1, max: 9 }),
      tags: generateRandomTags(1, 6, faker.number.int({ min: 1, max: 3 })),
      authorId: faker.number.int({ min: 1, max: 3 }),
    });
  }
  console.log("Fake articles generated");
  return articles;
};

const articles = generateArticles(10);

module.exports = {
  users,
  odonates,
  publications,
  settings,
  categories,
  tags,
  articles,
  newsletterEmails,
};
